import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ChatWidget from "@/components/ChatWidget";
import ConveyThisProvider from "@/components/ConveyThisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('vytara_theme') || 'default';
                  if (theme !== 'default') {
                    document.documentElement.classList.add('theme-' + theme);
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen overflow-x-hidden`}
        style={{ backgroundColor: 'var(--theme-background, #e8f7f5)' }}
      >
        {/* ConveyThis (loads once globally) */}
        <ConveyThisProvider />

        {/* App pages */}
        {children}

        {/* Chat widget */}
        <ChatWidget />
      </body>
    </html>
  );
}
